# Available commands : https://nikitabobko.github.io/AeroSpace/commands
after-startup-command = [
  'exec-and-forget borders active_color=0xFF7AA2F7 inactive_color=0xFF292E42 width=5.0 whitelist=kitty',
]
start-at-login = true

# Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

# Possible values: tiles|accordion
default-root-container-layout = 'tiles'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
# Drop it from your config, if you don't like this behavior
# See https://nikitabobko.github.io/AeroSpace/guide#on-focus-changed-callbacks
# See https://nikitabobko.github.io/AeroSpace/commands#move-mouse
# Fallback value (if you omit the key): on-focused-monitor-changed = []
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# You can effectively turn off macOS "Hide application" (cmd-h) feature by toggling this flag
# Useful if you don't use this macOS feature, but accidentally hit cmd-h or cmd-alt-h key
# Also see: https://nikitabobko.github.io/AeroSpace/goodies#disable-hide-app
automatically-unhide-macos-hidden-apps = true

[key-mapping]
preset = 'qwerty'

# Gaps between windows (inner-*) and between monitor edges (outer-*).
# Possible values:
# - Constant:     gaps.outer.top = 8
# - Per monitor:  gaps.outer.top = [{ monitor.main = 16 }, { monitor."some-pattern" = 32 }, 24]
#                 In this example, 24 is a default value when there is no match.
#                 Monitor pattern is the same as for 'workspace-to-monitor-force-assignment'.
#                 See:
#                 https://nikitabobko.github.io/AeroSpace/guide#assign-workspaces-to-monitors
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

[workspace-to-monitor-force-assignment]
5 = 'built-in'

[mode.main.binding]
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon,
#                   backtick, leftSquareBracket, rightSquareBracket, space, enter, esc,
#                   backspace, tab, pageUp, pageDown, home, end, forwardDelete,
#            mam       sectionSign (ISO keyboards only, european keyboards only)
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

ctrl-alt-shift-cmd-tab = ['mode move']
ctrl-alt-shift-cmd-space = ['mode move']

ctrl-alt-cmd-shift-n = ['workspace-back-and-forth']

ctrl-alt-cmd-shift-f = ['fullscreen']

ctrl-alt-cmd-shift-h = ['focus left']
ctrl-alt-cmd-shift-j = ['focus down']
ctrl-alt-cmd-shift-k = ['focus up']
ctrl-alt-cmd-shift-l = ['focus right']

ctrl-alt-cmd-shift-left = ['join-with left']
ctrl-alt-cmd-shift-down = ['join-with down']
ctrl-alt-cmd-shift-up = ['join-with up']
ctrl-alt-cmd-shift-right = ['join-with right']

ctrl-alt-cmd-shift-a = ['workspace 1']
ctrl-alt-cmd-shift-s = ['workspace 2']
ctrl-alt-cmd-shift-d = ['workspace 3']
ctrl-alt-cmd-shift-w = ['workspace 4']
ctrl-alt-cmd-shift-q = ['workspace 5']
ctrl-alt-cmd-shift-m = ['workspace M']
ctrl-alt-cmd-shift-o = ['workspace O']
ctrl-alt-cmd-shift-z = ['workspace Z']

ctrl-alt-cmd-shift-semicolon = ['resize smart +50']
ctrl-alt-cmd-shift-quote = ['resize smart -50']

# Check if Kitty is running. If yes, open a new window, if not start it.
ctrl-alt-cmd-shift-enter = [
  '''exec-and-forget osascript -e '
on is_running(appName)
	tell application "System Events" to (name of processes) contains appName
end is_running

if not is_running("kitty") then
	tell application "kitty" to activate
else
	tell application "System Events" to tell process "kitty"
		click menu item "New OS Window" of menu 1 of menu bar item "Shell" of menu bar 1
	end tell
end if'
''',
  'mode main',
]
ctrl-alt-cmd-shift-b = ['''exec-and-forget osascript -e '
on is_running(appName)
	tell application "System Events" to (name of processes) contains appName
end is_running

if not is_running("Safari") then
	tell application "Safari" to activate
else
	tell application "Safari"
		make new document
		activate
	end tell
end if'
''', 'mode main']
ctrl-alt-cmd-shift-e = ['''exec-and-forget osascript -e '
  tell application "Finder"
    make new Finder window
    activate
  end tell'
''', 'mode main']

[mode.move.binding]
ctrl-alt-cmd-shift-a = ['move-node-to-workspace 1', 'workspace 1']
ctrl-alt-cmd-shift-s = ['move-node-to-workspace 2', 'workspace 2']
ctrl-alt-cmd-shift-d = ['move-node-to-workspace 3', 'workspace 3']
ctrl-alt-cmd-shift-w = ['move-node-to-workspace 4', 'workspace 4']
ctrl-alt-cmd-shift-q = ['move-node-to-workspace 5', 'workspace 5']
ctrl-alt-cmd-shift-m = ['move-node-to-workspace M', 'workspace M']
ctrl-alt-cmd-shift-o = ['move-node-to-workspace O', 'workspace O']
ctrl-alt-cmd-shift-z = ['move-node-to-workspace Z', 'workspace Z']

a = ['workspace 1']
s = ['workspace 2']
d = ['workspace 3']
w = ['workspace 4']
q = ['workspace 5']
m = ['workspace M']
o = ['workspace O']
z = ['workspace Z']

ctrl-alt-cmd-shift-h = ['move left']
ctrl-alt-cmd-shift-j = ['move down']
ctrl-alt-cmd-shift-k = ['move up']
ctrl-alt-cmd-shift-l = ['move right']

h = ['focus left']
j = ['focus down']
k = ['focus up']
l = ['focus right']

left = ['join-with left']
down = ['join-with down']
up = ['join-with up']
right = ['join-with right']

period = ['layout tiles horizontal vertical']
comma = ['layout accordion horizontal vertical']
slash = ['layout floating tiling']

esc = 'mode main'
space = 'mode main'

[[on-window-detected]]
if.app-id = 'com.microsoft.Outlook'
run = ['move-node-to-workspace O']

[[on-window-detected]]
if.app-id = 'com.apple.mail'
run = ['move-node-to-workspace O']

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = ['move-node-to-workspace M']

[[on-window-detected]]
if.app-id = 'com.microsoft.Teams2'
run = ['move-node-to-workspace M']

[[on-window-detected]]
if.app-name-regex-substring = 'youtube'
run = ['move-node-to-workspace Z']

[[on-window-detected]]
if.app-id = 'org.whispersystems.signal-desktop'
run = ['move-node-to-workspace M']
