#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

# Load global styles, colors and icons
source "$CONFIG_DIR/globalstyles.sh"

# Set bar appearance and defaults
sketchybar --bar "${bar[@]}" --default "${item_defaults[@]}"

##### Adding Left Items #####
source "$ITEM_DIR/aerospace_spaces.sh"

sketchybar --add item front_app left \
           --set front_app icon.drawing=off script="$PLUGIN_DIR/front_app.sh" \
           --subscribe front_app front_app_switched

##### Adding Right Items #####
sketchybar --add item clock right \
           --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" icon.padding_left=8 label.padding_right=8 \
           --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" icon.padding_left=8 label.padding_right=8 \
           --subscribe volume volume_change \
           --add item battery right \
           --set battery update_freq=120 script="$PLUGIN_DIR/battery.sh" icon.padding_left=8 label.padding_right=8\
           --subscribe battery system_woke power_source_change

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
