[general]
import = [ "tokyo-night.toml" ] # or tokyo-night-storm.toml

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 0.95

[font]
size = 15.0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style  = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Italic"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style  = "Bold Italic"

[keyboard]
bindings = [
  # Cmd+1..9 => send Ctrl-b then digit (tmux default window selection)
  { key = "Key1", mods = "Command", chars = "\u00021" },
  { key = "Key2", mods = "Command", chars = "\u00022" },
  { key = "Key3", mods = "Command", chars = "\u00023" },
  { key = "Key4", mods = "Command", chars = "\u00024" },
  { key = "Key5", mods = "Command", chars = "\u00025" },
  { key = "Key6", mods = "Command", chars = "\u00026" },
  { key = "Key7", mods = "Command", chars = "\u00027" },
  { key = "Key8", mods = "Command", chars = "\u00028" },
  { key = "Key9", mods = "Command", chars = "\u00029" },
  { key = "T", mods = "Command", chars = "\u0002c" },
  { key = "W", mods = "Command", command = { program = "/bin/sh", args = ["-lc", "~/.config/alacritty/tmux-close-or-tmux.sh"] } },
  { key = "W", mods = "Command|Shift", chars = "\u0002d" },
  { key = "Return", mods = "Shift", chars = "\u001B\r" },
]
